### ISSUE TITLE
No se encuentran las imágenes hasta que se reinicie el servidor

### ISSUE THREAD

**Issue by ricorrales07** [ricorrales07/Inge1#2]
Cuando guardamos cualquier imagen, no se puede encontrar hasta que el servidor se reinicie. Estuve investigando, parece que esto se debe a que estamos guardando las imágenes en una carpeta que debería contener solo datos del servidor, no datos de los clientes. Los datos de clientes deberían completamente aparte de los datos del servidor.

No estoy muy seguro de cómo acomodar las imágenes en otra parte y que funcione en las máquinas de todos. Además, cambiar todos los sitios donde guardamos y cargamos imágenes implica muchos cambios.

**Comment by JuanRodJ** [comment]
No estoy muy seguro pero tal vez este post puede ayudar un poco https://stackoverflow.com/questions/1972242/auto-reload-of-files-in-node-js
